Fix `Error: Failed to add page binding with name ___pepr_cs: window['___pepr_cs'] already exists!`
When page.solveRecaptchas() is called multiple times, an error is thrown

```
Error: Failed to add page binding with name ___pepr_cs: window['___pepr_cs'] already exists!
```

In my test I use puppeteer@14.4.1 with its default Chrome, puppeteer-extra@3.3.4 and puppeteer-extra-plugin-recaptcha@3.6.8. I haven't tried other versions.